---
- name: Install applications I used
  hosts: localhost
  connection: local

  tasks:
    - name: Install base packages
      become: yes
      yum:
        name:
          - wget
          - firefox
          - patch
          - bat
        state: present

    - import_role:
        name: hashicorp
    - import_role:
        name: qemu
    - import_role:
        name: rpm-dev
    - import_role:
        name: spotify
    - import_role:
        name: gnome-terminal
    - import_role:
        name: cursors
    - import_role:
        name: fonts
    - import_role:
        name: gtk
    - import_role:
        name: kitty
    - import_role:
        name: neovim
    - import_role:
        name: wallpapers
